<?php
/**
 * Permet de passe les variables POST des requêtes Ajax en paramètre des fonctions des controlleurs.
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class EqnRecepteurAjax {


	/**
	 * @access public
	 * @param  $f3 
	 */

	public final  function addEquation($f3) {
            $eqn_manager = EquationManager::getInstance();
            $eqn = new Equation([
                    'id' => $f3->get('POST.id'),
                    'nom' => $f3->get('POST.nom'),
                    'om_code' => $f3->get('POST.eqn')]);
            $eqn_manager->save($eqn);
	}


	/**
	 * @access public
	 * @param  $f3 
	 */

	public final  function deleteEquation($f3) {

	}


	public final  function displayAll($f3) {
            $eqn_manager = EquationManager::getInstance();
            $f3->set('eqns', $eqn_manager->getAll());
            
            echo Template::instance()->render('templates/equation/liste_equations.htm');
        }


}
?>