<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Equation {

	/**
	 * 
	 * @var int
	 * @access protected
	 */
	protected  $id;

	/**
	 * Code OpenMath de l'équation
	 * @var string
	 * @access protected
	 */
	protected  $om_code;

	/**
	 * Nom de l'équation
	 * @var string
	 * @access protected
	 */
	protected  $nom;
        
        public function __construct($tableau) {
            $this->hydrate($tableau);
        }
        
        public function hydrate($tableau) {
            foreach ($tableau as $cle=>$valeur) {
                $setter = 'set'.ucfirst($cle);
                if(method_exists($this, $setter)) {
                    $this->$setter($valeur);
                }
            }
        }


	/**
	 * @access public
	 * @param int $id 
	 * @return void
	 */

	public final  function setId($id) {
            $this->id = $id;
	}


	/**
	 * @access public
	 * @return int
	 */

	public final  function getId() {
            return $this->id;
	}


	/**
	 * @access public
	 * @param string $om_code 
	 * @return void
	 */

	public final  function setOm_code($code) {
            $this->om_code = $code;
	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function getOm_code() {
            return $this->om_code;
	}


	/**
	 * @access public
	 * @param string $nom 
	 * @return void
	 */

	public final  function setNom($nom) {
            $this->Nom = $nom;
	}


	/**
	 * @access public
	 * @return string
	 */

	public final  function getNom() {
            return $this->Nom;
	}


}